# Generated by Django 2.1.7 on 2019-03-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milliard', '0009_auto_20190309_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('count_correct_answers', models.IntegerField(default=0)),
                ('money_won', models.IntegerField(default=0)),
            ],
        ),
    ]
