# Generated by Django 2.1.7 on 2019-03-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milliard', '0010_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='count_correct_answers',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='money_won',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
