# Generated by Django 2.1.7 on 2019-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milliard', '0012_auto_20190311_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='call_friend',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='fifty_fifty',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='help_peole',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
