# Generated by Django 2.1.7 on 2019-03-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milliard', '0013_auto_20190311_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='help_peole',
            new_name='help_people',
        ),
    ]
