# Generated by Django 2.1.7 on 2019-03-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milliard', '0015_question_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=50),
        ),
    ]
