# Generated by Django 2.1.7 on 2019-03-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milliard', '0016_auto_20190319_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=250, unique=True),
        ),
    ]
