# Generated by Django 2.1.7 on 2019-03-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milliard', '0017_auto_20190319_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=140, unique=True),
        ),
    ]
