# Generated by Django 2.1.7 on 2019-03-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milliard', '0018_auto_20190319_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=130, unique=True),
        ),
    ]
