# Generated by Django 2.1.7 on 2019-03-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milliard', '0021_auto_20190321_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=58),
        ),
    ]
