# Generated by Django 2.1.7 on 2019-03-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milliard', '0023_auto_20190321_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=50),
        ),
    ]
